version: '3.7'

services:

  data_platform:
    container_name: data_platform
    image: "lensesio/fast-data-dev"
    ports:
      - "9092:9092"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "2181:2181"
      - "3030:3030"
      - "9001:9001"
    environment:
      - "SAMPLEDATA=0"
      - "RUNNING_SAMPLEDATA=0"
      - "RUNTESTS=0"
      - "DISABLE_JMX=1"
      - "SUPERVISORWEB=1"
      - "ADV_HOST=127.0.0.1"