version: '3.7'

services:

  data_platform:
    container_name: data_platform
    image: "lensesio/fast-data-dev"
    ports:
      - "9092:9092"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "2181:2181"
      - "3030:3030"
      - "9001:9001"
    environment:
      - "SAMPLEDATA=0"
      - "RUNNING_SAMPLEDATA=0"
      - "RUNTESTS=0"
      - "DISABLE_JMX=1"
      - "SUPERVISORWEB=1"
      - "ADV_HOST=127.0.0.1"
    networks:
      - services-network

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - services-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    depends_on:
      - "mongo"
    ports:
      - 8181:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
      - services-network

  mysql:
    image: mysql:5.7.34
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=booking_db
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306
    networks:
      - services-network

  phpmyadmin:
    image: phpmyadmin:5.1.1
    container_name: phpmyadmin
    restart: always
    depends_on:
      - "mysql"
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - services-network

  order:
    build: order/
    image: order
    container_name: order
    ports:
      - 8084:8084
    networks:
      - services-network
    depends_on:
      - mongo
    environment:
      - DATABASE_HOST=mongo

  booking:
    build: booking/
    image: booking
    container_name: booking
    restart: on-failure
    ports:
      - 8085:8085
    networks:
      - services-network
    depends_on:
      - mysql
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306

networks:
  services-network:
    driver: "bridge"