version: '3.7'

services:

  data_platform:
    container_name: data_platform
    image: "lensesio/fast-data-dev"
    ports:
      - "9092:9092"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "2181:2181"
      - "3030:3030"
      - "9001:9001"
    environment:
      - "SAMPLEDATA=0"
      - "RUNNING_SAMPLEDATA=0"
      - "RUNTESTS=0"
      - "DISABLE_JMX=1"
      - "SUPERVISORWEB=1"
      - "ADV_HOST=data_platform"
    networks:
      - services-network

  mongo:
    image: mongo:latest
    container_name: mongo_saga
    restart: always
    ports:
      - "27017:27017"
    networks:
      - services-network

  mysql:
    image: mysql:5.7.34
    container_name: mysql_saga
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=booking_db
    ports:
      - 3306:3306
    networks:
      - services-network

  postgres:
    image: postgres:9.6.22-alpine
    container_name: postgres_saga
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=payment_db
    ports:
      - 5432:5432
    networks:
      - services-network

  orchestrator:
    build: orchestrator/
    image: orchestrator
    container_name: orchestrator
    networks:
      - services-network
    depends_on:
      - data_platform
      - order
      - booking
      - payment
    environment:
      - KAFKA_URL=data_platform:9092
      - SCHEMA_REGISTRY_URL=http://data_platform:8081

  order:
    build: order/
    image: order
    container_name: order
    ports:
      - 8084:8084
    networks:
      - services-network
    depends_on:
      - mongo
      - data_platform
    environment:
      - DATABASE_HOST=mongo
      - KAFKA_URL=data_platform:9092
      - SCHEMA_REGISTRY_URL=http://data_platform:8081

  booking:
    build: booking/
    image: booking
    container_name: booking
    restart: on-failure
    ports:
      - 8085:8085
    networks:
      - services-network
    depends_on:
      - mysql
      - data_platform
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - KAFKA_URL=data_platform:9092
      - SCHEMA_REGISTRY_URL=http://data_platform:8081

  payment:
    build: payment/
    image: payment
    container_name: payment
    restart: on-failure
    ports:
      - 8086:8086
    networks:
      - services-network
    depends_on:
      - postgres
      - data_platform
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - KAFKA_URL=data_platform:9092
      - SCHEMA_REGISTRY_URL=http://data_platform:8081

networks:
  services-network:
    driver: "bridge"