server:
  port: 8084

spring:
  data:
    mongodb:
      host: ${DATABASE_HOST:localhost}
      port: ${DATABASE_PORT:27017}
      database: ${DATABASE_NAME:orders_db}

  kafka:
    bootstrap-servers:
      - ${KAFKA_URL:127.0.0.1:9092}
    consumer:
      group-id: order
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      security:
        protocol: "PLAINTEXT"
      schema:
        registry:
          url: ${SCHEMA_REGISTRY_URL:http://127.0.0.1:8081}

order:
  topics:
    order-created: br.com.concrete.order_created_v1
    order-cancel: br.com.concrete.order_cancel_v1
    order-confirm: br.com.concrete.order_confirm_v1